### ISSUE TITLE
running brakeman on a set of files only may miss warnings

### ISSUE THREAD

**Issue by jdoconnor** [mmozuras/pronto-brakeman#6]
I've seen examples of where brakeman can miss mass assignment warnings in rails 3 when using the only_files option. I have a fork currently that runs against the entire project, then allows messages_for to filter out the warnings not applicable to the change set that seems to work. Would the project be interested in the contribution?

**Comment by mmozuras** [comment]
@jdoconnor thanks for creating the issue :bow:. But no, I don't think that belongs with Pronto. It wouldn't work so well on bigger projects, which is the primary case for its existence.
