### ISSUE TITLE
Update brakeman version - maybe be more flexible?

### ISSUE THREAD

**Issue by david-a-wheeler** [mmozuras/pronto-brakeman#9]
The currently-specified version of brakeman is obsolete.

I think in this case, pronto would be better served by using ">=" instead of "~>" when specifying the version of Brakeman.  That'd be more flexible, and would avoid this problem in the future.

Thanks!

**Comment by mmozuras** [comment]
Done :smile: 

https://github.com/mmozuras/pronto-brakeman/commit/0db7e4ee9aac2782a1abf969bb2b6e375364d4f1

Thanks :bow:
